extends:
  - ./base/cifar100_order1.yaml
module:
  model:
    backbone: Swin-B
  adapt_blocks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  pet_cls: Adapter
  pet_kwargs:
    down_sample: 5
    mode: parallel
    scale: null
